version: "2.4"

services:
  website:
    container_name: tiki_website
    build:
      context: ./website
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${WEB_PORT:-3001}:3000
      - ${WEB_DEBUG_PORT:-9228}:9229
    volumes:
      - ./website:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WDS_SOCKET_PORT: 3001
  api:
    container_name: tiki_api
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${API_PORT:-3000}:3000
      - ${API_DEBUG_PORT:-9229}:9229
    volumes:
      - ./api/src:/app/src
    env_file: ./api/.env
  db:
    container_name: tiki_db
    image: postgres:12
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - ./db/init-local-db.sql:/docker-entrypoint-initdb.d/docker-postgres-init.sql
      - ./db/tikidata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
volumes:
  tikidata:
