CREATE USER tiki_admin WITH ENCRYPTED PASSWORD 'tiki';
CREATE DATABASE tiki;
\connect tiki
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;
GRANT ALL PRIVILEGES ON DATABASE tiki TO tiki_admin;